title: Traffic Incident Management
description: This portfolio represents my growing experience in coding and problem-solving, with a specific focus on traffic incident management. It includes projects I've worked on as a student, including coursework, personal experiments, and collaborative efforts aimed at developing innovative solutions for improving traffic safety and resource allocation. 
theme: jekyll-theme-cayman 
